apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: node-env
  name: env-vars
data:
  NODE_ENV: "production"
  CONTAINER: "true"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: env-vars
        - name: CONTAINER
          valueFrom:
            configMapKeyRef:
              key: CONTAINER
              name: env-vars
        image: node-service-jumpstart
        imagePullPolicy: IfNotPresent
        name: node-service-jumpstart
        ports:
        - containerPort: 8080
        resources: {}
