apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: angular-jumpstart
build:
  artifacts:
  - image: nginx-angular-jumpstart
    context: .
    sync: 
      # A local build will update dist and sync it to the container
      manual:
      - src: "./dist"
        dest: "/usr/share/nginx/html"
    docker:
      # Referencing a dev version of the Dockerfile so that the speed is better
      # Will build app locally which is then copied into the image
      # Much faster than doing a multi-stage build as you would for production
      dockerfile: .docker/nginx.dev.dockerfile
  - image: node-service-jumpstart
    context: .
    docker:
      dockerfile: .docker/node.dockerfile
deploy:
  kubectl:
    manifests:
    - .k8s/*.yml
